- name: Ensure Docker is installed
  package:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create a Docker volume for the registry
  docker_volume:
    name: registry

- name: Run the Docker registry container
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    network_mode: host
    env:
      REGISTRY_HTTP_ADDR: "0.0.0.0:4000"
    volumes:
      - registry:/var/lib/registry
