all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_port: 22
    ansible_ssh_private_key_file: /root/ary.pem
    populate_inventory_to_hosts_file: true
  children:
    all:
      children:
        localhost:
          hosts:
            localhost:
              ansible_host: 127.0.0.1
              ansible_hostname: localhost
        control:
          hosts:
            controller01:
              ansible_host: 192.168.88.16
              access_ip: 172.16.18.24
              ansible_hostname: controller01
            controller02:
              ansible_host: 192.168.88.37
              access_ip: 172.16.18.88
              ansible_hostname: controller02
            controller03:
              ansible_host: 192.168.88.50
              access_ip: 172.16.18.29
              ansible_hostname: controller03
        compute:
          hosts:
            compute01:
              ansible_host: 192.168.88.72
              access_ip: 172.16.18.70
              ansible_hostname: compute01
            compute02:
              ansible_host: 192.168.88.38
              access_ip: 172.16.18.49
              ansible_hostname: compute01
        network:
          hosts:
            network01:
              ansible_host: 192.168.88.33
              access_ip: 172.16.18.46
              ansible_hostname: network01
            network02:
              ansible_host: 192.168.88.28
              access_ip: 172.16.18.78
              ansible_hostname: network02
        storage:
          hosts:
            controller01:
              ansible_host: 192.168.88.16
              access_ip: 172.16.18.24
              ansible_hostname: controller01
            controller02:
              ansible_host: 192.168.88.37
              access_ip: 172.16.18.88
              ansible_hostname: controller02
            controller03:
              ansible_host: 192.168.88.50
              access_ip: 172.16.18.29
              ansible_hostname: controller03
