all:
  vars:
    ansible_ssh_port: 22
    ansible_ssh_private_key_file: /root/ary.pem
    populate_inventory_to_hosts_file: true
  children:
    all:
      children:
        control:
          hosts:
            controller01:
              ansible_host: 192.168.88.64
              access_ip: 172.16.18.74
              ansible_hostname: controller01
            controller02:
              ansible_host: 192.168.88.73
              access_ip: 172.16.18.45
              ansible_hostname: controller02
            controller03:
              ansible_host: 192.168.88.39
              access_ip: 172.16.18.62
              ansible_hostname: controller03
        compute:
          hosts:
            compute01:
              ansible_host: 192.168.88.52
              access_ip: 172.16.18.76
              ansible_hostname: compute01
            compute02:
              ansible_host: 192.168.88.49
              access_ip: 172.16.18.17
              ansible_hostname: compute01
        network:
          hosts:
            network01:
              ansible_host: 192.168.88.79
              access_ip: 172.16.18.16
              ansible_hostname: network01
            network02:
              ansible_host: 192.168.88.77
              access_ip: 172.16.18.80
              ansible_hostname: network02
        storage:
          hosts:
            controller01:
              ansible_host: 192.168.88.64
              access_ip:
              ansible_hostname: controller01
            controller02:
              ansible_host: 192.168.88.73
              access_ip: 172.16.18.45
              ansible_hostname: controller02
            controller03:
              ansible_host: 192.168.88.39
              access_ip:
              ansible_hostname: controller03
