- hosts: all
  become: true
  gather_facts: yes
  name: make nodes ready to deploy
  roles:
    - { role: pre-deploy, tags: ["pre"] }
    - { role: kolla-user, tags: ["kolla-user"] }
    - { role: docker, when: "'localhost' in group_names", tags: ["docker"] }
    - { role: private-registry, when: "'localhost' in group_names", tags: ["reg"] }
    - { role: pre-kolla, when: "'localhost' in group_names", tags: ["kolla"] }
    - { role: nova-presetup, when: inventory_hostname != 'localhost' }
    - { role: cinder-presetup, when: inventory_hostname != 'localhost' }
    - { role: glance-presetup, when: inventory_hostname != 'localhost' }
    - { role: ovn-presetup, when: inventory_hostname != 'localhost' }
    - { role: fluentd-presetup, when: inventory_hostname != 'localhost' }
    - { role: cron-presetup, when: inventory_hostname != 'localhost' }
    - { role: certs-presetup, when: inventory_hostname != 'localhost' }
