- name: Update all packages
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_apt_url }}"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Check Docker Compose Version
  command: docker-compose --version
  register: dc_version

- debug:
    var: dc_version.stdout_lines
