---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install required system packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - libffi-dev
      - gcc
      - libssl-dev
      - git
    state: present
  become: true

- name: Ensure pip is upgraded
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Clone Kolla Ansible from Git
  git:
    repo: "{{ kolla_ansible_git_repo }}"
    dest: "{{ kolla_clone_dest }}"
    version: "{{ kolla_ansible_branch }}"
    force: yes

- name: Install Kolla-Ansible Python dependencies
  pip:
    requirements: "{{ kolla_clone_dest }}/requirements.txt"

- name: Install Kolla-Ansible itself
  shell: |
    pip install kolla-ansible && kolla-ansible install-deps
  args:
    creates: "bin/kolla-ansible"
  register: kolla_ansible_install
  changed_when: kolla_ansible_install.rc == 0 and "Requirement already satisfied" not in kolla_ansible_install.stdout

- name: Ensure /etc/kolla exists
  file:
    path: /etc/kolla
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: Copy Kolla example configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kolla_config_dir }}"
    force: no
  with_items:
    - "{{ kolla_etc_examples_path }}/kolla/globals.yml"
    - "{{ kolla_etc_examples_path }}/kolla/passwords.yml"

- name: Get checksum of current passwords.yml
  stat:
    path: "{{ kolla_passwords_file }}"
    checksum_algorithm: sha1
  register: current_pwd_file

- name: Get checksum of example passwords.yml
  stat:
    path: "{{ kolla_etc_examples_path }}/kolla/passwords.yml"
    checksum_algorithm: sha1
  register: example_pwd_file

- name: Generate passwords with kolla-genpwd if current passwords.yml matches example
  command: kolla-genpwd
  register: kolla_genpwd_result
  when: current_pwd_file.stat.checksum == example_pwd_file.stat.checksum
  changed_when: kolla_genpwd_result.rc == 0 and
                "Existing passwords.yml not modified" not in kolla_genpwd_result.stderr
  failed_when: kolla_genpwd_result.rc != 0 and
               "Existing passwords.yml not modified" not in kolla_genpwd_result.stderr

- name: Copy multinode inventory
  copy:
    src: "{{ kolla_clone_dest }}/ansible/inventory/multinode"
    dest: "/root/multinode"
    remote_src: yes
